# Generated by Django 4.1.5 on 2023-01-21 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('closed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=70)),
                ('hospitalName', models.CharField(default='', max_length=70)),
                ('businessHourFri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businessHourFri', to='findMyDoctor.businesshour')),
                ('businessHourMon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businessHourMon', to='findMyDoctor.businesshour')),
                ('businessHourSat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businessHourSat', to='findMyDoctor.businesshour')),
                ('businessHourSun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businessHourSun', to='findMyDoctor.businesshour')),
                ('businessHourThu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businessHourThu', to='findMyDoctor.businesshour')),
                ('businessHourTue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businessHourTue', to='findMyDoctor.businesshour')),
                ('businessHourWed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businessHourWed', to='findMyDoctor.businesshour')),
                ('lunchTime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunchTime', to='findMyDoctor.businesshour')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('expiredAt', models.DateTimeField()),
                ('isAccepted', models.BooleanField(default=False)),
                ('doctorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctorId', to='findMyDoctor.doctor')),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientId', to='findMyDoctor.patient')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='medicalDepartment',
            field=models.ManyToManyField(blank=True, null=True, related_name='medicalDepartment', to='findMyDoctor.medicaldepartment'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='noImbursedMedicalDepartment',
            field=models.ManyToManyField(blank=True, null=True, related_name='noImbursedMedicalDepartment', to='findMyDoctor.medicaldepartment'),
        ),
    ]
