# Generated by Django 3.2.16 on 2023-01-18 06:31

from django.db import migrations, models
import djongo.models.fields
import findMyDoctor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('hospitalName', models.CharField(default='', max_length=70)),
                ('medicalDepartment', djongo.models.fields.ArrayField(model_container=findMyDoctor.models.MedicalDepartment, model_form_class=findMyDoctor.models.MedicalDepartmentForm)),
                ('noImbursedMedicalDepartment', djongo.models.fields.ArrayField(model_container=findMyDoctor.models.MedicalDepartment, model_form_class=findMyDoctor.models.MedicalDepartmentForm)),
                ('businessHour', djongo.models.fields.ArrayField(model_container=findMyDoctor.models.BusinessHour, model_form_class=findMyDoctor.models.BussinessHourForm)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
